services:
  app-back:
    image: bloglist-back-dev
    build:
      context: ./backend/.
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
    container_name: bloglist-back-dev
  
  app-front:
    image: bloglist-front-dev
    build:
      context: ./frontend/.
      dockerfile: dev.Dockerfile
    environment:
      - VITE_APP_BACKEND_URL=http://localhost:3003/api
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: bloglist-front-dev