version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - 6378:6379
    volumes:
      - ./redis_data:/data

  app:
    image: todo-back-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
    container_name: todo-back-dev